name: Run Sales Forecast

on:
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  run_forecast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl numpy pandas pmdarima scipy

    - name: Run script
      run: python sales_forecast.py

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: sales-result
        path: sales.xlsx
        retention-days: 7  # Хранение файла 7 дней
