name: Run Sales Forecast
on: workflow_dispatch  # Ручной запуск
jobs:
  run_forecast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl numpy pandas pmdarima scipy
    - name: Run script
      run: python sales_forecast.py
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: sales-result
        path: sales.xlsx
