name: Run Sales Forecast

on:
  workflow_dispatch:

jobs:
  run_forecast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl==3.1.2 numpy==1.24.3 pandas==2.0.3 pmdarima==2.0.4 scipy==1.10.1

    - name: List files
      run: ls -la  # Для отладки

    - name: Run script
      run: python -W ignore sales_forecast.py  # Игнорируем предупреждения

    - name: Upload result
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: sales-result
        path: sales.xlsx
        retention-days: 7
